api_platform:
    title: Ecentria API Skeleton

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    formats:
        jsonapi:  ['application/vnd.api+json']
        html:     ['text/html']
        json:     ['application/json']

    error_formats:
        jsonapi: [ 'application/vnd.api+json' ]

    swagger:
        versions: [3]

    show_webby: false

    collection:
        pagination:
            client_items_per_page: true # Disabled by default
            items_per_page_parameter_name: itemsPerPage # Default value

    path_segment_name_generator: api_platform.path_segment_name_generator.dash
