apiVersion: v1
kind: Pod
metadata:
    name: ${POD_LABEL}
spec:
    priorityClassName: high-priority
    volumes:
        - name: app
          emptyDir: {}
        - name: ssh-key
          secret:
              secretName: kaniko-ssh-key
              defaultMode: 256
        - name: kaniko-config
          secret:
              secretName: kaniko-config

    initContainers:
        - name: app-build
          image: ${REGISTRY_HOST}/ecentria/staging/staging-context-fetcher:latest
          volumeMounts:
              - name: app
                mountPath: /api-skeleton-php
              - name: ssh-key
                mountPath: /root/.ssh/id_rsa
                subPath: id_rsa
                readOnly: true
          resources:
              requests:
                  cpu: 250m
                  memory: 250Mi
          command:
              - /bin/sh
              - -c
              - ${COMMAND}

    containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          volumeMounts:
              - name: app
                mountPath: /api-skeleton-php
              - name: kaniko-config
                mountPath: /kaniko/.docker/
          workingDir: /api-skeleton-php
          resources:
              requests:
                  cpu: 1350m
                  memory: 1150Mi
          args: ["--context=dir://.",
                 "--dockerfile=ci/docker/image/php-fpm/Dockerfile",
                 "--destination=${REGISTRY_HOST}/${PROJECT_NAME}/php-fpm-app:${IMAGE_TAG}"]
    restartPolicy: Never
